import React from 'react';

class Spinner extends React.Component {
  render() {
    return (
      <svg
        className='spinner'
        style={{
          margin: '0 auto',
          background: 'none',
          display: 'block',
          shapeRendering: 'auto',
          width: '100px',
          height: '100px',
          viewBox: '0 0 100 100',
          preserveAspectRatio: 'xMidYMid',
        }}>
        <g transform='translate(50 42)'>
          <g transform='scale(0.8)'>
            <g transform='translate(-50 -50)'>
              <polygon fill='#4dd0e1' points='72.5 50 50 11 27.5 50 50 50'>
                <animateTransform
                  attributeName='transform'
                  type='rotate'
                  repeatCount='indefinite'
                  dur='1s'
                  values='0 50 38.5;360 50 38.5'
                  keyTimes='0;1'
                />
              </polygon>
              <polygon fill='#ff5252' points='5 89 50 89 27.5 50'>
                <animateTransform
                  attributeName='transform'
                  type='rotate'
                  repeatCount='indefinite'
                  dur='1s'
                  values='0 27.5 77.5;360 27.5 77.5'
                  keyTimes='0;1'
                />
              </polygon>
              <polygon fill='#212121' points='72.5 50 50 89 95 89'>
                <animateTransform
                  attributeName='transform'
                  type='rotate'
                  repeatCount='indefinite'
                  dur='1s'
                  values='0 72.5 77.5;360 72 77.5'
                  keyTimes='0;1'
                />
              </polygon>
            </g>
          </g>
        </g>
        {/* //  [ldio] generated by https://loading.io/  */}
      </svg>
    );
  }
}
export default Spinner;
